### ISSUE TITLE
scroll-view 宽度计算有问题，超过宽度显示异常，如图

### ISSUE THREAD

**Issue by klower** [dcloudio/hello-uniapp#101]
![image](https://github.com/user-attachments/assets/d29bdd26-68dc-4646-a627-08d7a33c174c)

**Comment by Otto-J** [comment]
提供下单页面源码吧，你截图，做了哪些修改？我使用HBuilderX alpha 最新版，创建 hellouniapp 打开你截图的页面渲染正常
