### ISSUE TITLE
为什么没有package.json文件？

### ISSUE THREAD

**Issue by smoothdvd** [dcloudio/hello-uniapp#13]

**Comment by hbcui1984** [comment]
uni-app新版已开放package.json，详见：https://uniapp.dcloud.io/collocation/package

另，hello uni-app中也已新增package.json，用于演示钉钉小程序平台开发， 见：https://github.com/dcloudio/hello-uniapp/commit/a389e687f3ee2db1d11176c62d6b8aa063b059a5

**Comment by jukrb0x** [comment]
你管这个叫开放？dc这个公司真让我大开眼界。把一个正常的前端项目要搞得支离破碎，你们开发者是不懂IDE的I是Integrated的意思吗？什么情况下会开两个IDE写同一份代码？

![image](https://user-images.githubusercontent.com/15688641/167267617-26a6ca3e-7f46-484d-b62d-c0ba286e7d9d.png)

至于代码提示强大？您（开发者们）真的用过webstorm吗？不仅没有就事论事，这不是在论教派是在说啥？

![image](https://user-images.githubusercontent.com/15688641/167267981-98568055-7e60-4bbc-8f6e-58b223362961.png)

至于拿这个市占率说事，一个打开项目就疯狂弹登录窗口的软件，我只能开怀大笑了。
