### ISSUE TITLE
https://unidemo.dcloud.net.cn/payment/wx/mp

### ISSUE THREAD

**Issue by crodling** [dcloudio/hello-uniapp#18]
服务端的包装实现代码是否能开放出来学习一下的？

**Comment by Wangyaqi** [comment]
github上面就有  [https://github.com/dcloudio/H5P.Server](https://github.com/dcloudio/H5P.Server)

**Comment by crodling** [comment]
> 我们的github上面就有 https://github.com/dcloudio/H5P.Server

demo是错的，折腾死人了。

Pay方法里面得调整，不然一直报支付签名校验失败

 var timeStamp = MakeTimestamp();
            var prepayId = xe.Element("prepay_id").Value;
            nstr = xe.Element("nonce_str").Value;
            Hashtable paySignReqHandler = new Hashtable();
            paySignReqHandler.Add("appId", this.AppId);
            //paySignReqHandler.Add("partnerid", this.MchId);
            //paySignReqHandler.Add("prepayid", prepayId);
            paySignReqHandler.Add("nonceStr", nstr);
            paySignReqHandler.Add("package", "prepay_id="+ prepayId);
            paySignReqHandler.Add("signType", "MD5");
            paySignReqHandler.Add("timeStamp", timeStamp.ToString());
