### ISSUE TITLE
package.json 中是否可以提供依赖项和启动命令？

### ISSUE THREAD

**Issue by xnng** [dcloudio/hello-uniapp#19]
只能用那什么 builder 软件开发吗？没有在 package.json 中发现依赖配置，能否支持命令启动，而不是玩自己的那一套。

**Comment by Wangyaqi** [comment]
可以用cli创建项目，这个里面的package.json只是自定义钉钉小程序平台的示例  [使用cli创建项目](https://uniapp.dcloud.io/quickstart?id=_2-%e9%80%9a%e8%bf%87vue-cli%e5%91%bd%e4%bb%a4%e8%a1%8c)

**Comment by xnng** [comment]
好的，了解了
