### ISSUE TITLE
求官方uni-app蓝牙发送接收示例

### ISSUE THREAD

**Issue by b7ur** [dcloudio/hello-uniapp#20]
按[官方文档](https://uniapp.dcloud.io/api/system/ble)写了蓝牙发送，也返回了write成功信息，但硬件没有收到。很奇怪。
官方演示了
- deviceid,
- serviceId
- characteristicId    
但没有写如何发送，求官方示例的
请问serviceId是获得的第一个uuid吗

**Comment by StrivingRabbit** [comment]
在hello-uniapp中有蓝牙使用示例
