### ISSUE TITLE
作者你好，我在使用hello-uniapp运行在android和iphone手机上发现本地网页中所有按钮点击无效。

### ISSUE THREAD

**Issue by chenwenxian** [dcloudio/hello-uniapp#21]

**Comment by Wangyaqi** [comment]
使用的HBuilderX版本是多少

**Comment by chenwenxian** [comment]
2.3.3.20190923

**Comment by chenwenxian** [comment]
![image](https://user-images.githubusercontent.com/5305181/67145790-05196c80-f2b7-11e9-8c03-989a44d20e82.png)

**Comment by chenwenxian** [comment]
有提示更新版本，是需要更新版本才能解决这个问题么？

**Comment by chenwenxian** [comment]
我先试更新看看。
![image](https://user-images.githubusercontent.com/5305181/67145820-47db4480-f2b7-11e9-9fb4-7fb756b2fda4.png)

**Comment by Wangyaqi** [comment]
你可以更新一下试试，我用新版没有复现你说的问题

**Comment by chenwenxian** [comment]
已经更新了，但是还是不可以。

**Comment by chenwenxian** [comment]
![image](https://user-images.githubusercontent.com/5305181/67145945-a48b2f00-f2b8-11e9-9517-c6671525737f.png)

**Comment by chenwenxian** [comment]
你使用的是那个版本？

**Comment by Tinnaso** [comment]
你在说啥




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chenwenxian"<notifications@github.com&gt;; 
发送时间: 2019年10月19日(星期六) 晚上9:38
收件人: "dcloudio/hello-uniapp"<hello-uniapp@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [dcloudio/hello-uniapp] 作者你好，我在使用hello-uniapp运行在android和iphone手机上发现本地网页中所有按钮点击无效。 (#21)




你使用的是那个版本？

**Comment by Wangyaqi** [comment]
你的hello uniapp是哪里的，HBuilderX创建的还是在这个仓库下的，运行到安卓还是IOS

**Comment by chenwenxian** [comment]
运行到安卓和ios真机环境下是无效的。

**Comment by chenwenxian** [comment]
在github下载的。

**Comment by chenwenxian** [comment]
![image](https://user-images.githubusercontent.com/5305181/67146026-49a60780-f2b9-11e9-8f0d-ad1a8b98309d.png)

**Comment by Tinnaso** [comment]
别来问我了，问我干吗，我啥都没写




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王亚琪"<notifications@github.com&gt;; 
发送时间: 2019年10月19日(星期六) 晚上9:39
收件人: "dcloudio/hello-uniapp"<hello-uniapp@noreply.github.com&gt;; 
抄送: "Tinnaso"<1584815412@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [dcloudio/hello-uniapp] 作者你好，我在使用hello-uniapp运行在android和iphone手机上发现本地网页中所有按钮点击无效。 (#21)




你的hello uniapp是哪里的，HBuilderX创建的还是在这个仓库下的，运行到安卓还是IOS

**Comment by Wangyaqi** [comment]
还是没能复现，手机联网了吗？本地网页不正常的话，网络网页正常吗

**Comment by chenwenxian** [comment]
可以复现，问题还是存在的。本地网页和网络网页都不可以。手机是连接WIFI的

**Comment by CheJJ** [comment]
> 别来问我了，问我干吗，我啥都没写
> […](#)

人家没问你

**Comment by chenwenxian** [comment]
我只测试了3台手机都不可以，iphone X、iphone Xr和oppo A77

**Comment by Wangyaqi** [comment]
自己写一个简单的试试看，hello uniapp里面的本地网页和网络网页都用了一个在线的js，可能是你网络环境有点特殊这个js加载失败了，多测试测试看能不能大致确定一下可能的原因，我这隔着屏幕瞎猜有点难搞

**Comment by chenwenxian** [comment]
这两个都有提示。
![image](https://user-images.githubusercontent.com/5305181/67146457-c89d3f00-f2bd-11e9-9e12-4fb85533f42a.png)
![image](https://user-images.githubusercontent.com/5305181/67146462-d9e64b80-f2bd-11e9-8b82-1268ea69d5a8.png)

**Comment by chenwenxian** [comment]
说明脚本已经是有加载到的，已经调用了uni.switchTab方法。但无效。

**Comment by Wangyaqi** [comment]
把编译后的`unpackage/dist/dev/app-plus`打包发上来

**Comment by StrivingRabbit** [comment]
还有什么问题吗？
