### ISSUE TITLE
uniapp-vue项目编译报错：_http_outgoing.js The header content contains invalid characters

### ISSUE THREAD

**Issue by Smile-Liu** [dcloudio/hello-uniapp#22]
求助大神。
运行 -> 运行到浏览器 -> Chrome，然后出现下面的报错内容。

17:13:48.722 项目 'pro-h5' 开始编译...
17:13:56.910  INFO  Starting development server...
17:14:12.212 _http_outgoing.js:494
17:14:12.216     throw new TypeError('The header content contains invalid characters');
17:14:12.216     ^
17:14:12.221 TypeError: The header content contains invalid characters
17:14:12.221     at validateHeader (_http_outgoing.js:494:11)
17:14:12.225     at ServerResponse.setHeader (_http_outgoing.js:498:3)
17:14:12.225     at setHeader (D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:98:15)
17:14:12.230     at D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:124:7
17:14:12.230     at Array.forEach (<anonymous>)
17:14:12.256     at Array.writeHeaders (D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:119:35)
17:14:12.257     at ClientRequest.<anonymous> (D:\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:175:22)
17:14:12.261     at emitOne (events.js:116:13)
17:14:12.262     at ClientRequest.emit (events.js:211:7)
17:14:12.267     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
17:14:12.267     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
17:14:12.271     at Socket.socketOnData (_http_client.js:440:20)
17:14:12.278     at emitOne (events.js:116:13)
17:14:12.282     at Socket.emit (events.js:211:7)
17:14:12.287     at addChunk (_stream_readable.js:263:12)
17:14:12.292     at readableAddChunk (_stream_readable.js:250:11)

**Comment by StrivingRabbit** [comment]
[点击查看](https://blog.csdn.net/fboypsx/article/details/50789473?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control)

**Comment by StrivingRabbit** [comment]
使用的是什么版本的HBuilder？运行官方示例是否也是报这个错？看起来是HX使用的node_module报的错
