### ISSUE TITLE
// #ifdef, 如何加入or的条件

### ISSUE THREAD

**Issue by liuyingqq123** [dcloudio/hello-uniapp#23]
package.json中

> "uni-app": {
    "scripts": {
      "mp-doctor": {
        "title": "医生",
        "env": {
          "UNI_PLATFORM": "mp-weixin"
        },
        "define": {
          "MP-DOCTOR": true
        }
      },
      "mp-patient": {
        "title": "患者",
        "env": {
          "UNI_PLATFORM": "mp-weixin"
        },
        "define": {
          "MP-PATIENT": true
        }
      },
> 

在js中区分这两个环境, 想添加OR的条件, 但是下面的用法不好使, 应该如何使用?
// #ifdef MP-DOCTOR || MP-PATIENT
// #endif

**Comment by StrivingRabbit** [comment]
你好，可以详细的描述一下你的使用场景吗？两个条件都是mp-weixin
