### ISSUE TITLE
uni.chooseImage  fail回调直接获取权限的逻辑错误

### ISSUE THREAD

**Issue by zhruith** [dcloudio/hello-uniapp#25]
在/pages/api/image页面，uni.chooseImage的fail回调，fail的原因也有可能是取消选择图片，输出为"chooseImage:fail cancel"，取消选择不需要进入获取权限页。因此需要加个判断如下：
...............
...............
fail: (err) => {
-----------------------------------------------------------------------
console.log(err.errMsg)   // "chooseImage:fail cancel"
	if (err.errMsg.substr(-6) !== "cancel") {
-----------------------------------------------------------------------
	// #ifdef APP-PLUS
	if (err['code'] && err.code !== 0 && this.sourceTypeIndex === 2) {
	this.checkPermission(err.code);
..................
..................

**Comment by StrivingRabbit** [comment]
感谢反馈，已修复
