### ISSUE TITLE
input收起软键盘却不能聚焦

### ISSUE THREAD

**Issue by jiaqiangmochn** [dcloudio/hello-uniapp#27]
由于用uniapp开发pda扫描枪 ，不太需要键盘输入，都是input框聚焦由扫描枪扫条形码输入值。目前问题是：input框聚焦 不管是手动点软键盘收起按钮 还是Uni.hidekeyboard() 都会失去焦点，这是为什么，可不可以有收起软键盘同时，还不失去焦点仍然聚焦的情况？

**Comment by zhetengbiji** [comment]
前期的版本安卓默认收起键盘时是不会失去焦点的（比如2.2.2），iOS会失去焦点。由于一些用户反馈安卓收起键盘时无法失去焦点，以及行为同iOS不一致，后期版本改为了收取键盘即失去焦点。
你可以尝试使用早期版本（发布需离线打包）。

**Comment by NiggerMo** [comment]
> 前期的版本安卓默认收起键盘时是不会失去焦点的（比如2.2.2），iOS会失去焦点。由于一些用户反馈安卓收起键盘时无法失去焦点，以及行为同iOS不一致，后期版本改为了收取键盘即失去焦点。
> 你可以尝试使用早期版本（发布需离线打包）。

哦哦好的，我去试试前期版本的看看，谢谢

**Comment by NiggerMo** [comment]
切回2.2.2 可以了感谢@zhetengbiji。现在还有个问题就是@focus事件里 
//#ifdef APP-PLUS
				uni.hideKeyboard()
				plus.key.hideSoftKeybord()
//#endif	
无论哪种收起软键盘好像都收不起来。实际开发完的app给用户用是直接外界扫描设备部需要这个软键盘，软键盘弹起来反而页面会被顶飞，所以尝试手动代码收起失败不知道有没有其他大哥也遇过这样的需求

**Comment by zhetengbiji** [comment]
> 切回2.2.2 可以了感谢@zhetengbiji。现在还有个问题就是@Focus事件里
> //#ifdef APP-PLUS
> uni.hideKeyboard()
> plus.key.hideSoftKeybord()
> //#endif
> 无论哪种收起软键盘好像都收不起来。实际开发完的app给用户用是直接外界扫描设备部需要这个软键盘，软键盘弹起来反而页面会被顶飞，所以尝试手动代码收起失败不知道有没有其他大哥也遇过这样的需求

试试延迟调用此API，另外尝试配置adjust-position试试

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
