### ISSUE TITLE
安卓app在红米note4上无法调用背景音频

### ISSUE THREAD

**Issue by 13557432464** [dcloudio/hello-uniapp#29]
官方的线上hello-app可以，但是hbuilderX里下载的示例hello不行，不知道是不是环境问题。

**Comment by StrivingRabbit** [comment]
你好，可以提供一下运行环境吗？
我使用了红米1，webview 71.0.3578.141。
运行 HBuilder X 3.0.7 -alpha 中下载的hello-uniapp实例。
访问 内置组件 -> 媒体组件 -> audio  和  接口 -> 媒体 -> 音频。都是可以播放的。
