### ISSUE TITLE
钉钉小程序安卓机无法显示

### ISSUE THREAD

**Issue by jditlee** [dcloudio/hello-uniapp#31]
钉钉小程序安卓机无法显示，运行的是uniapp的官方demo，底部tabar能显示，中间的白屏

**Comment by jditlee** [comment]
钉钉第三方个人应用是可以显示的，钉钉企业内部应用无法显示

**Comment by StrivingRabbit** [comment]
使用企业内部应用预览至安卓手机，没有发现相关情况，可以详细的描述一下使用场景吗？
