### ISSUE TITLE
app nvue页面使用 文本太长会导致闪退

### ISSUE THREAD

**Issue by csq0668** [dcloudio/hello-uniapp#32]
在app nvue页面使用 文本字符串太长会导致闪退

**Comment by chuzhixin** [comment]
vue学习搭框架必备,集合了所有的vue技术栈,希望帮助到大家

演示地址:http://chu1204505056.gitee.io/vue-admin-beautiful

源码地址:https://github.com/chuzhixin/vue-admin-beautiful,

pc端效果比手机端会好很多，欢迎star

**Comment by csq0668** [comment]
我也发现了这个问题

**Comment by StrivingRabbit** [comment]
你好，我在nvue中的text标签内写了，5000左右文本，没有闪退。可以详细描述一下你的使用场景吗？
