### ISSUE TITLE
扫码下载的客户端功能在本项目中找不到代码

### ISSUE THREAD

**Issue by jackgreentemp** [dcloudio/hello-uniapp#33]
你好，扫码下载了"HelloUniApp@v2.5.10.apk"，安装打开之后，底部tab栏是"社区"、“实例”、“我的”，但是在本项目代码里没找到相关代码，是有另外一个项目地址吗？

**Comment by hbcui1984** [comment]
含问答社区部分的代码是另外一版，但其中的实例选项卡内容和本工程师一致的。
