### ISSUE TITLE
nvue页面用webview原生，IOS下，加载的网页中a[target=_blank]链接无法打开

### ISSUE THREAD

**Issue by wuliaolll** [dcloudio/hello-uniapp#37]
IOS下，nvue页面用webview原生，webview加载的网页中如果有a标签，且target=_blank，这样的链接无法打开，是不是生成的源码中WKWebView在创建策略上没有设置为在同一webview中打开新页面。

Android没有此问题。

**Comment by StrivingRabbit** [comment]
已反馈，如果有结果我会再次说明

**Comment by xiaohuapunk** [comment]
请在官方网站反馈一下这个问题吧提供一下示例方便排查问题 [https://ask.dcloud.net.cn/#all](https://ask.dcloud.net.cn/#all)

**Comment by StrivingRabbit** [comment]
已发布到3.1.0 -alpha。

**Comment by xiaohuapunk** [comment]
此问题已经在 HBuilderX 13.1.0+版本修复

**Comment by fktest** [comment]
4.0.8复现此问题
