### ISSUE TITLE
关于PC端H5适配问题

### ISSUE THREAD

**Issue by Aton5859** [dcloudio/hello-uniapp#43]
您好，
我看项目主页ReadMe文件提供的H5体验对于web兼容非常好，但是直接clone该项目到本地运行或者打包H5之后对于PC端的适配就都没有了，请问我是缺少了什么配置或者操作吗？
![微信截图_20201111171907](https://user-images.githubusercontent.com/28555389/98793026-43de0f80-2442-11eb-9468-2359e2fc7c7e.png)

**Comment by zhetengbiji** [comment]
应该是没注意到有不同的分支

**Comment by Aton5859** [comment]
> 应该是没注意到有不同的分支

请问应该用哪个分支？我尝试了下vue3分支的，下载下来都运行不了，另一个dev应该不是了吧......
![12324239](https://user-images.githubusercontent.com/28555389/98825249-3d19c180-246f-11eb-9c8f-18547c286303.png)
安装了vuex还是报错
