### ISSUE TITLE
你这写的是个锤子Demo，老子真的服了

### ISSUE THREAD

**Issue by ZJH9Rondo** [dcloudio/hello-uniapp#46]

**Comment by ZJH9Rondo** [comment]
尼玛，package.json都有问题，你拿出来给谁用，还是官方Demo！README连指引都没有，二维码扫了都加载失败，1.4k的star是你妈淘宝刷的吧

**Comment by Fasttian** [comment]
增加了新特性，升级到最新版 [HBuilderX](https://dcloud.io/hbuilderx.html) 尝试

**Comment by ZJH9Rondo** [comment]
{
    "uni-app": {
        "scripts": {
            "mp-dingtalk": { 
                "title":"钉钉小程序", 
                "env": { 
                    "UNI_PLATFORM": "mp-alipay" 
                },
                "define": { 
                    "MP-DINGTALK": true 
                }
            }
        }
    }
}

摆脱，你看看你的package.json 好吗？

**Comment by Fasttian** [comment]
不用package.json ，项目依赖我们的 IDE HBuilderX 去运行，你对 uni-app不太了解，先通过社区[快速上手文档](https://uniapp.dcloud.net.cn/quickstart)去创建 hello-uniapp 吧

**Comment by ZJH9Rondo** [comment]
> 不用package.json ，项目依赖我们的 IDE HBuilderX 去运行，你对 uni-app不太了解，先通过社区[快速上手文档](https://uniapp.dcloud.net.cn/quickstart)去创建 hello-uniapp 吧

大哥，谁规定开发一定要用你们的HbuilderX，你Demo说必须用这个了？我用VsCode不行？你这Demo都不符合最基本的常识，你告诉我是我不了解？这就是所谓的外包全家桶？

**Comment by 490626721** [comment]
傻逼DEMO
