### ISSUE TITLE
对于popup的意见

### ISSUE THREAD

**Issue by lihaotian0607** [dcloudio/hello-uniapp#5]
希望可以增加弹出后禁止页面滚动的选项
还有个bug就是页面过长的时候 popup 会出现在顶部....

**Comment by wakaryry** [comment]
同求。每次popup后页面还能下面的页面还能在拖动popup内容的时候滚动。给强迫症用户一种心里不爽的卸载冲动。

**Comment by Wangyaqi** [comment]
现在已经修改了
