### ISSUE TITLE
通过 @vue/cli 创建项目，缺少 sass-loader

### ISSUE THREAD

**Issue by 50ways2sayhard** [dcloudio/hello-uniapp#53]
❯ npm run serve

> my-project@0.1.0 serve /mnt/d/projects/my-project
> npm run dev:h5

> my-project@0.1.0 dev:h5 /mnt/d/projects/my-project
> cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve

请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
 INFO  Starting development server...

 ERROR  Failed to compile with 1 error                                                                                                                                                                10:54:26 AM

Failed to resolve loader: sass-loader
You may need to install it.

**Comment by zhetengbiji** [comment]
创建项目的时候是否选择了 sass？如未选，请安装。

**Comment by 50ways2sayhard** [comment]
> 创建项目的时候是否选择了 sass？如未选，请安装。

没有选的机会，只能选模板

**Comment by zhetengbiji** [comment]
npm i node-sass@4 sass-loader@7

**Comment by GuryYu** [comment]
添加这两个依赖

"sass": "^1.32.13",
"sass-loader": "^10.2.0",

**Comment by 50ways2sayhard** [comment]
手动添加依赖可以解决，但是希望安装模板的时候能处理全部依赖，而不是要手动添加

**Comment by mehaotian** [comment]
问题已经处理
