### ISSUE TITLE
导入到微信小程序调试后,显示找不到app.json

### ISSUE THREAD

**Issue by dybxin** [dcloudio/hello-uniapp#54]
[ app.json 文件内容错误] app.json: app.json 未找到(env: Windows,mp,1.05.2105170; lib: 2.0.4)

**Comment by XFFanny** [comment]
我用HBuilder 调试也遇到了，需要设置 小程序需要开启设置--> 安全设置 --> 服务端口开启

**Comment by codexu** [comment]
导入路径确认一下，是否是 unpackage/dist/dev/mp-weixin
