### ISSUE TITLE
rpx转换失败

### ISSUE THREAD

**Issue by jaiden-home** [dcloudio/hello-uniapp#59]
run起来之后写了一些css发现不支持rpx，不清楚哪里出了问题
![image](https://user-images.githubusercontent.com/64107132/136536209-3836d4b9-0bf2-4e95-84ac-e7412e3d89ed.png)

**Comment by codexu** [comment]
如果 @vue/cli 4.0 是 bate 版本可以降到 3.0，目前不要升级到 5.0 版本，或者 npm update 更新一下依赖，都可以解决这个问题
