### ISSUE TITLE
mpvuePicker.vue不修改值确认时报错

### ISSUE THREAD

**Issue by tianyouhui** [dcloudio/hello-uniapp#6]
设置mpvuePicker.vue展示时，点击确定按钮直接关闭，而不改变初始值，就会报错，请帮忙确认一下，谢谢。
错误如下：

01:57:21.526 57:20.752  6039  6039 I console : TypeError: Cannot read property 'label' of undefined
01:57:21.546 57:20.752  6039  6039 I console :     at VueComponent._getPickerLabelAndValue (uni-app:///components/mpvue-picker/mpvuePicker.vue?vue&type=script&lang=js&?0594:326:57)
01:57:21.570  (Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/mpvue/index.js:249:36)
01:57:21.590 57:20.752  6039  6039 I console :     at VueComponent.pickerConfirm (uni-app:///components/mpvue-picker/mpvuePicker.vue?vue&type=script&lang=js&?0594:244:21)
01:57:21.610 57:20.752  6039  6039 I console :     at Array.boundFn (Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/mpvue/index.js:249:63)
01:57:21.633  (Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/mpvue/index.js:5550:40)
01:57:21.655 57:20.752  6039  6039 I console :     at e.handleProxy (Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/mpvue-page-factory/index.js:76:24)

**Comment by tianyouhui** [comment]
滚动到其它值再 点击确认关闭就正常

**Comment by StrivingRabbit** [comment]
现在是否还有这个问题？
