### ISSUE TITLE
直接clone下来安装依赖后无法启动项目。

### ISSUE THREAD

**Issue by manson-2020** [dcloudio/hello-uniapp#60]
![image](https://user-images.githubusercontent.com/43368308/138668645-aa9529e4-54bb-4934-9113-e2ded95b9e11.png)

**Comment by manbanpan** [comment]
利用HBuilderX 创建新项目选择Hello uniapp 然后导出资源. 放入iOS项目 运行成功 页面是白屏 什么原因???
<img width="406" alt="image" src="https://user-images.githubusercontent.com/16233145/164146239-45041470-1430-4300-b72e-6df899771bd5.png">

**Comment by manson-2020** [comment]
感觉现在vue3版本问题特别多，正式版还是用vue2吧。
