### ISSUE TITLE
vue3版本的uniapp 编译css的图片资源时，有些图片并没有转化为base64格式

### ISSUE THREAD

**Issue by iluwgl** [dcloudio/hello-uniapp#65]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/39099191/154843626-2c387cba-d739-43ea-a652-56c005248ea6.png">
vue3版本的uniapp 编译css的图片资源时，有图片并没有转化为base64格式
我看了其他都变成base64格式了，就这个没有编译过去

我只测试了vue3版本 用的运行命令时
yarn run dev:mp-weixin

**Comment by codexu** [comment]
微信小程序小于 40kb 会转 base64

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
