### ISSUE TITLE
在vue2中点击事件出现了如下错误

### ISSUE THREAD

**Issue by benfenglee** [dcloudio/hello-uniapp#67]
Property or method "__HOLDER__" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

**Comment by codexu** [comment]
请补充在哪里点击，发生了这个错误

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
