### ISSUE TITLE
在ios中，输入密码的input框闪动的问题

### ISSUE THREAD

**Issue by zhong1998** [dcloudio/hello-uniapp#68]
https://user-images.githubusercontent.com/49584064/168562012-1f79c32f-258b-4966-af22-b881b1cf6980.mp4

输入密码的时候，在输入带有数字的输入框，会出现闪动问题，附上视频，希望解决这个问题。

when i write password,i find i finish the password input, i write something in number input, it flashes

**Comment by codexu** [comment]
iOS 的话，使用 nvue 就可以解决此问题

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
