### ISSUE TITLE
markdown 加粗、````修饰等会换行

### ISSUE THREAD

**Issue by Hunterfish** [dcloudio/hello-uniapp#7]
markdown对于加粗修饰和````修饰的文本显示换行效果
![snipaste_20190420_214824](https://user-images.githubusercontent.com/25543945/56458185-0b856500-63b6-11e9-88ad-1c84b69e6e5a.jpg)

**Comment by StrivingRabbit** [comment]
现在是否还有问题？如果有的话，请详细描述一下使用场景
