### ISSUE TITLE
运行hello-uniapp导致蓝屏死机

### ISSUE THREAD

**Issue by cgr20171202** [dcloudio/hello-uniapp#70]
我的电脑是2020年的联想笔记本，外加自己买的海康威视固态硬盘。系统是win11家庭中文版21H2.操作系统版本22000.739。在使用hbuilderX的时候多次发生蓝屏死机，重启后海康威视ssd就读不到盘。
包括注册分包路由，还有运行hello-uniapp新项目。但是运行其他项目没有问题。只要一运行hello-uniapp或者是其他项目注册分包路由就会蓝屏死机。windows终止代码是STSTEM_SERVICE_EXCEPTION。此外打开这个helloapp的uni-modules则有时候会蓝屏。
在海康威视ssd读不了盘的情况下还是会发生蓝屏。

**Comment by Otto-J** [comment]
如果仍有问题，请 reopen。欢迎在 uni-app 仓库和 ask 社区继续反馈，
