### ISSUE TITLE
ifndef APP-PLUS 没有编译进去

### ISSUE THREAD

**Issue by wozzup** [dcloudio/hello-uniapp#72]
https://github.com/dcloudio/hello-uniapp/blob/master/pages/template/tabbar/tabbar.nvue#L284

上面 `tabbar.nvue` 文件 `<style>` 标签中的那些 `/* #ifndef APP-PLUS */` 编译 android 一个都没编译进去

**Comment by codexu** [comment]
ifndef APP-PLUS 是不包括 App nvue，注意这是 if*n*def

**Comment by wozzup** [comment]
😅 尴尬了，我没有看清楚。新手上路，请多多指教。

我是用 android miui13 运行了一下，发现和web表现不一样，打开控制台调试了一下，发现很多css没有编译进去，比如 `class="uni-tab-item"` 的样式没有  `display: inline-block;` 造成页面显示不完整。
