### ISSUE TITLE
引入uView2.0版本报错

### ISSUE THREAD

**Issue by Reputation-Liberty** [dcloudio/hello-uniapp#74]
按照官方文档的步骤
1、yarn add node-sass -D
2、yarn add sass-loader@10 -D
3、yarn add uview-ui
4、main.js引入Vue之后 import uView from 'uview-ui'
5、main.js引入Vue之后 Vue.use(uView)
6、uni.scss中 @import 'uview-ui/theme.scss';
7、App.vue中 <style lang="scss"> /*每个页面公共css */ @import "uview-ui/index.scss"; @import "./vendor/colorui/main.css"; @import "./vendor/colorui/icon.css"; /* @import "./assets/app.scss"; 你的项目css */ </style>
8、配置了easycom
9、vue.config.js中增加transpileDependencies: ['uview-ui']
![QQ截图20221001154118](https://user-images.githubusercontent.com/67351888/193398806-023d75d6-8123-4d84-8884-82f6e232136c.png)
![QQ截图20221001154136](https://user-images.githubusercontent.com/67351888/193398809-3cc50b3a-5a9f-4c1a-99d7-c7f8389711a5.png)

**Comment by Otto-J** [comment]
如果仍有问题，请 reopen。欢迎在 uni-app 仓库和 ask 社区继续反馈，
