### ISSUE TITLE
钉钉小程序uni-form系统错误

### ISSUE THREAD

**Issue by oulp** [dcloudio/hello-uniapp#76]
钉钉小程序进入uni-form表单，系统错误，正在排查
<img width="322" alt="image" src="https://user-images.githubusercontent.com/8519009/198229630-2bca5ad1-0764-43d1-9959-f4de72db7d30.png">

**Comment by hbcui1984** [comment]
这个报错是钉钉基座提示的，重启钉钉试试。

**Comment by Otto-J** [comment]
如果仍有问题，请 reopen 并提供复现工程。欢迎在 uni-app 仓库和 ask 社区继续反馈，
