### ISSUE TITLE
uni.chooselocation not support IOS

### ISSUE THREAD

**Issue by blindperson** [dcloudio/hello-uniapp#79]
when use uni.chooselocation in ios, we will get this, no error message, and no list, so lead to can't use OK button
![image](https://user-images.githubusercontent.com/43574443/225279120-e63923ec-cfac-4206-9d3a-30d7e91af18a.png)

**Comment by Otto-J** [comment]
经过我测试使用最新的 HBuilderX alpha 运行 vue2/vue3 版本都 hello uniapp 可以正常使用。如果仍有问题，请 reopen 并提供复现工程。欢迎在 uni-app 仓库和 ask 社区继续反馈，
