### ISSUE TITLE
可以提供一个支持vue3+vite的单元测试方案吗

### ISSUE THREAD

**Issue by Moonofweisheng** [dcloudio/hello-uniapp#80]

**Comment by sunpm** [comment]
是的，可以添加 vitest 方案吗

**Comment by virtual1680** [comment]
现在还没有吗？？

**Comment by virtual1680** [comment]
现在还没有吗？？

**Comment by w123angmeng** [comment]
> _No description provided._
按uni-app 官网给的搭了下vite + vue3 自动化测试环境，npm run test:h5 没问题；npm run test:mp-weixin 静态资源确实
demo： https://github.com/w123angmeng/vite-vue3-autotest-demo
也提了issue：https://github.com/dcloudio/hello-uniapp/issues/86

你那边有啥vue3 自动化测试有啥解决方案吗？

**Comment by Otto-J** [comment]
如果是运行到 H5 平台，vue3 项目可以自行集成 vitest 或者 jest 进行测试，和普通的 web 项目无异。如果仍有问题，请 reopen。欢迎在 uni-app 仓库和 ask 社区继续反馈，
