### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ilvhmfer** [dcloudio/hello-uniapp#82]
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
11:35:14.650 SassError: Invalid CSS after "... 0 3px 6px -4px": expected expression (e.g. 1px, bold), was "#0000001f, 0 6px 16"
11:35:14.656         on line 460 of F:\demos\uni\hello-uniapp\uni_modules\uni-table\components\uni-th\filter-dropdown.vue
11:35:14.657 >> 	box-shadow: 0 3px 6px -4px #0000001f, 0 6px 16px #00000014, 0 9px 28px 8px #0

**Comment by Otto-J** [comment]
感谢反馈，现在编译还有问题吗，我使用最新版本编译 hello-uniapp 的 vue2 和 vue3 两个版本都正常，这个问题是否已经被修复过了。如果有问题请继续补充，欢迎 open issues
