### ISSUE TITLE
这有打算兼容鸿蒙系统吗

### ISSUE THREAD

**Issue by jayden-qiu** [dcloudio/hello-uniapp#83]

**Comment by Otto-J** [comment]
官方对鸿蒙 Next 的态度：

> uts语言是iOS和Android都支持的，但uvue引擎的iOS还在开发中，所以目前uni-app x只支持Android。
> 目前uni-app x的web版处于测试阶段、iOS版处于开发阶段。所以uni-app x的web版很快会上线，而iOS版也计划在插件大赛结束前上线。
> 很多开发者关心鸿蒙next的适配。uni-app x使用uts，而鸿蒙使用arkTs，都是ts的变种，适配并不复杂。DCloud和鸿蒙团队一直保持着沟通，会在合适的时机启动。
> 更多需求，欢迎到需求墙投票：[vote.dcloud.net.cn/#/?name=uni…](https://link.juejin.cn/?target=https%3A%2F%2Fvote.dcloud.net.cn%2F%23%2F%3Fname%3Duni-app%2520x)

作者：CHB
链接：https://juejin.cn/post/7306694295247175719
来源：稀土掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
