### ISSUE TITLE
ERROR in ./src/components/api-set-tabbar.nvue?vue&type=style&index=0&id=d3cc0f72&scoped=true&lang=css

### ISSUE THREAD

**Issue by fzhange** [dcloudio/hello-uniapp#89]
按照README 指引

`npm install -g @vue/cli
vue create -p dcloudio/uni-preset-vue my-project
cd my-project
npm run dev:h5
`
浏览器打开 http://192.168.20.18:8080/ 直接报错 

![image](https://github.com/dcloudio/hello-uniapp/assets/62326668/4332a249-591a-4c1f-9555-388f165003b3)

**Comment by fzhange** [comment]
Compiled with problems:
×
ERROR in ./src/components/api-set-tabbar.nvue?vue&type=style&index=0&id=d3cc0f72&scoped=true&lang=css& (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-12[0].rules[0].use[1]!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader/index.js??clonedRuleSet-12[0].rules[0].use[2]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-12[0].rules[0].use[3]!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/index.js??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-scoped-loader/index.js!./src/components/api-set-tabbar.nvue?vue&type=style&index=0&id=d3cc0f72&scoped=true&lang=css&)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/apple/mks/my-project/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Users/apple/mks/my-project/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/apple/mks/my-project/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/apple/mks/my-project/node_modules/postcss-loader/dist/index.js:96:17)
ERROR in ./src/pages/API/animation/animation.vue?vue&type=style&index=0&id=25dd86bb&scoped=true&lang=css& (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-12[0].rules[0].use[1]!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader/index.js??clonedRuleSet-12[0].rules[0].use[2]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-12[0].rules[0].use[3]!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/index.js??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-scoped-loader/index.js!./src/pages/API/animation/animation.vue?vue&type=style&index=0&id=25dd86bb&scoped=true&lang=css&)

**Comment by Otto-J** [comment]
我使用最新的文档测试，可以正常启动 vue-cli 项目，可能问题已经解决了。如果仍有问题，请 reopen。欢迎在 uni-app 仓库和 ask 社区继续反馈，
