### ISSUE TITLE
可视化创建的项目，怎么总报错啊

### ISSUE THREAD

**Issue by elarbor** [dcloudio/hello-uniapp#90]
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/fb015e4c-cbf8-4955-b817-628fff776352)

然后npm安装了一些插件：
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/4c584bfe-7c87-468c-a037-42595293f8bf)

能正常运行，但是时不时的，没规律，就偶尔报错：
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/3714f90e-99e1-43be-a822-21f16d7aa8b0)

一报错我就：
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/c312f749-4e49-4ead-aa2f-7968d1168c96)

**Comment by Otto-J** [comment]
看到报错是资源被锁了，是不是云同步的文件夹，普通目录不会出现这个问题，你可以放到根目录之外再试试。如果仍有问题，请 reopen。欢迎在 uni-app 仓库和 ask 社区继续反馈，
