### ISSUE TITLE
uniapp自动化测试支持部署到服务器上 命令行去跑测试用例吗？

### ISSUE THREAD

**Issue by w123angmeng** [dcloudio/hello-uniapp#91]
想咨询下 uniapp自动化测试支持部署到服务器上定时任务去跑测试用例吗？目前遇到的问题是npm run test:mp-weixin 本地电脑跑有微信开发者工具能看到测试报告；如果是服务器linux jenkins自动部署，执行npm run test:mp-weixin，没有微信开发者工具，是不是就不行？或者有啥别的方案不？
有遇到同样场景需要解决的伙伴没？ 方便的话 交流一下

查到微信小程 miniprogram-ci （若需在不依赖开发者工具场景如自身业务工程流水线上进行小程序项目上传、预览，则推荐使用 miniprogram-ci。[https://developers.weixin.qq.com/miniprogram/dev/devtools/cli.html）](https://developers.weixin.qq.com/miniprogram/dev/devtools/cli.html%EF%BC%89)

**Comment by Lgowen** [comment]
无意中看到该issue，想请教一下是通过什么方案在小程序上去执行测试用例的呀。有什么推荐的参考测试方案嘛

**Comment by Otto-J** [comment]
比较简单的方案还是准备 mac/windows 虚拟机。微信小程序开发工具只提供 windows 和 mac 系统下载
