### ISSUE TITLE
编译小程序报错Error: Vue3 项目暂不支持当前小程序

### ISSUE THREAD

**Issue by LiJiaPeng001** [dcloudio/hello-uniapp#95]
<img width="600" alt="image" src="https://github.com/user-attachments/assets/8f760980-6d93-47ee-86cf-7f68d4630da7">
请问下该项目是必须使用hbuilderX才可以编译小程序吗？

**Comment by Otto-J** [comment]
提供个复现工程吧，在 Uni-app 仓库或者 ask 社区，HBuilderX 和 cli 都可以正常运行到微信小程序平台，不确定你到工程修改了哪些内容
