### ISSUE TITLE
uni-app x 能否给出一个 tabBar blurEffect 的例子

### ISSUE THREAD

**Issue by WuYunlong** [dcloudio/hello-uniapp#96]
我这边按照文档一直无效

**Comment by Otto-J** [comment]
你可以参考 [文档](https://doc.dcloud.net.cn/uni-app-x/collocation/pagesjson.html#pages-tabbar) 和 [文档2](https://uniapp.dcloud.net.cn//tutorial/app-blureffect.html) 进行测试。
如果仍有问题，请 reopen。欢迎在 uni-app 仓库和 ask 社区继续反馈，
