### ISSUE TITLE
hbuildx创建的依赖在哪，怎么升级啊，rpx翻译成了乱码%?20?%

### ISSUE THREAD

**Issue by zkhh666** [dcloudio/hello-uniapp#97]
hbuildx创建的依赖在哪，怎么升级啊，rpx翻译成了乱码%?20?%

**Comment by Otto-J** [comment]
感谢反馈，在 uni-app 仓库新建一条 issues 吧，并提供一个简单的复现工程。提供更多信息，有助于定位和解答你的问题。
