### ISSUE TITLE
uniapp-vue2的项目如何在linux搭建的jenkins环境上 进行自动化测试

### ISSUE THREAD

**Issue by jlinkcamera** [dcloudio/hello-uniapp#99]
我们的uniapp项目已经转换成vue-cli形式, 已完成ci上打包, 发布流程
目前卡在UI自动化测试上, 一直没有找到好的实践方案
@Otto-J O  大佬 给点建议吧

**Comment by Otto-J** [comment]
刚看到，可以在 uni-app 仓库进行提问。这个你想测试到那个平台进行自动化测试？
